theme = "dracula_at_night"

[editor]
scrolloff = 2
mouse = false
middle-click-paste = false
scroll-lines = 3
shell = ["sh", "-c"]
line-number = "absolute"
cursorline = true
cursorcolumn = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
auto-format = false
auto-save = false
idle-timeout = 250
completion-trigger-len = 1
# completion-replace = false
auto-info = true
true-color = true
# undercurl=false
rulers = [80]
bufferline = "never"
color-modes = true
# text-width = 80
# workspace-lsp-roots = []

[editor.statusline]
# left = ["mode", "file-name", "file-modification-indicator", "file-encoding", "file-line-ending", "file-type", "version-control"]
left = ["mode", "file-name", "file-encoding", "file-line-ending", "file-type"]
center = ["spinner", "diagnostics", "workspace-diagnostics", ]
right = ["selections", "primary-selection-length", "separator", "position", "total-line-numbers", "separator", "position-percentage" ]
separator = "|"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
# enable = true
display-messages = true
auto-signature-help = true
# display-inlay-hints = true
display-signature-help-docs = true
# snippets = true
# goto-reference-include-declaration = true

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "block"

[editor.file-picker]
hidden = false
follow-symlinks = true
# deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
# max-depath = None

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

# [editor.soft-wrap]
# enable = true
# max-wrap = 20
# max-indent-retain = 40
# wrap-indicator = '↪'
# wrap-at-text-width = false

[keys.normal]
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"
X   = "extend_line_above"

[keys.insert]
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"

[keys.select]
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"
